---
title: "RWorksheet4c in R"
author: ""
date: "2025-12-10"
output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(ggplot2)
library(dplyr)
library(RColorBrewer)   
library(readxl)
library(writexl)
```

## 1. MPG Dataset
```{r}
data(mpg)
write.csv(mpg, "mpg.csv", row.names = FALSE)
```
```{r}
mpg <- read.csv("mpg.csv", stringsAsFactors = FALSE)
mpg
```
```{r}
str(mpg)
```

## 2. Models by Manufacturer
```{r}
mpg %>%
  group_by(manufacturer) %>%
  summarise(models = n_distinct(model))
```
```{r}
unique_models <- mpg %>%
  group_by(manufacturer) %>%
  summarise(unique_models = n_distinct(model)) %>%
  arrange(desc(unique_models))

unique_models
```
```{r}
ggplot(unique_models, aes(x = reorder(manufacturer, -unique_models), y = unique_models)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  xlab("Manufacturer") + 
  ylab("Number of Unique Models") +
  ggtitle("Number of Unique Models by Manufacturer") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
ggplot(mpg, aes(x = reorder(manufacturer, model, function(x) length(unique(x))), y = model)) +
  geom_point() +
  xlab("Manufacturer") + 
  ylab("Model") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## 3. Top 20 Models
```{r}
top_20 <- head(mpg, 20)

ggplot(top_20, aes(x = model, y = year)) +
  geom_point() +
  xlab("Model") + 
  ylab("Year") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## 4. Car Model Frequency
```{r}
mpg %>%
  group_by(model) %>%
  summarise(count = n()) %>%
  arrange(desc(count))
```
```{r}
top_20_models <- mpg %>%
  group_by(model) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  head(20)

ggplot(top_20_models, aes(x = reorder(model, -count), y = count, fill = model)) +
  geom_bar(stat = "identity") +
  xlab("Model") + 
  ylab("Number of Cars") +
  ggtitle("Top 20 Car Models by Number of Cars") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "none") +
  scale_fill_manual(values = colorRampPalette(brewer.pal(12, "Set3"))(20))
```
```{r}
ggplot(top_20_models, aes(x = model, y = count, fill = model)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  xlab("Model") + 
  ylab("Number of Cars") +
  ggtitle("Top 20 Car Models by Number of Cars") +
  theme(axis.text.y = element_text(size = 9), legend.position = "none")
```

## 5. Cylinders vs Displacement
```{r}
ggplot(mpg, aes(x = cyl, y = displ, color = displ)) +
  geom_point() +
  ggtitle("Relationship between No. of Cylinders and Engine Displacement") +
  xlab("Number of Cylinders") + 
  ylab("Engine Displacement") +
  scale_color_gradient(low = "blue", high = "red")
```

## 6. Displacement vs Highway MPG
```{r}
ggplot(mpg, aes(x = displ, y = hwy, color = displ)) +
  geom_point() +
  ggtitle("Relationship between Engine Displacement and Highway MPG") +
  xlab("Engine Displacement (L)") + 
  ylab("Highway MPG") +
  scale_color_gradient(low = "blue", high = "red")
```

## 7. Traffic Data
```{r}
traffic_data <- data.frame(
  Date = as.Date('2025-11-01') + 0:9,
  Location = rep(c("Intersection A", "Intersection B"), each = 5),
  Vehicles = c(120, 150, 130, 160, 140, 200, 210, 190, 205, 220),
  Average_Speed = c(35.5, 34.2, 36.0, 33.8, 34.5, 32.0, 31.5, 33.0, 30.8, 29.5)
)

write.csv(traffic_data, "traffic.csv", row.names = FALSE)
traffic <- read.csv("traffic.csv", stringsAsFactors = FALSE)
```
```{r}
str(traffic)
```
```{r}
intersection_a <- traffic[traffic$Location == "Intersection A", ]
intersection_b <- traffic[traffic$Location == "Intersection B", ]

print(intersection_a)
print(intersection_b)
```
```{r}
ggplot(traffic, aes(x = Date, y = Vehicles, color = Location, group = Location)) +
  geom_line() +
  geom_point() +
  xlab("Date") + 
  ylab("Number of Vehicles") +
  ggtitle("Traffic Over Time by Junction") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## 8. Alexa Dataset
```{r}
alexa <- data.frame(
  rating = sample(1:5, 100, replace = TRUE),
  date = seq(as.Date("2024-01-01"), by = "day", length.out = 100),
  verified_reviews = sample(c("Great product", "Good", "Average", "Poor"), 100, replace = TRUE),
  feedback = sample(0:1, 100, replace = TRUE),
  variation = sample(c("Black", "White", "Charcoal Fabric", "Heather Gray Fabric"), 100, replace = TRUE)
)

write_xlsx(alexa, "alexa-file.xlsx")
alexa <- read_excel("alexa-file.xlsx")
```
```{r}
str(alexa)
```
```{r}
alexa %>%
  group_by(variation) %>%
  summarise(total = n())
```
```{r}
ggplot(alexa, aes(x = variation, fill = variation)) +
  geom_bar() +
  xlab("Variation") + 
  ylab("Count") +
  ggtitle("Count of Each Alexa Variation") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "none")
```
```{r}
ggplot(alexa, aes(x = date)) +
  geom_histogram(bins = 30, fill = "steelblue") +
  xlab("Date") + 
  ylab("Number of Reviews") +
  ggtitle("Alexa Reviews Over Time")
```
```{r}
ggplot(alexa, aes(x = factor(rating), fill = factor(rating))) +
  geom_bar() +
  xlab("Rating") + 
  ylab("Count") +
  ggtitle("Distribution of Alexa Ratings") +
  scale_fill_brewer(palette = "Set3") +
  theme(legend.position = "none")
```