---
output:
  pdf_document: default
  html_document: default
---
shoe_data <- data.frame(
  ShoeSize = c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5,
               13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 7.5, 8.5, 10.5, 8.5, 10.5, 11.0, 9.0, 13.0),
  Height = c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0, 64.0, 74.5, 67.0, 71.0, 
             71.0, 77.0, 72.0, 59.0, 62.0, 72.0, 66.0, 64.0, 67.0, 73.0, 69.0, 72.0, 70.0, 
             69.0, 70.0),
  Gender = c("F", "F", "F", "F", "M", "F", "F", "F", "M", "F", "M", "F", "M", "M", "M", 
             "M", "F", "F", "M", "F", "F", "F", "M", "F", "M", "M", "M", "M")
)

str(shoe_data)
summary(shoe_data)

males <- shoe_data[shoe_data$Gender == "M", ]
females <- shoe_data[shoe_data$Gender == "F", ]

print(males)
print(females)

mean_shoe_size <- mean(shoe_data$ShoeSize)
mean_height <- mean(shoe_data$Height)

print(paste("Mean Shoe Size:", mean_shoe_size))
print(paste("Mean Height:", mean_height))

correlation <- cor(shoe_data$ShoeSize, shoe_data$Height)
print(paste("Correlation:", correlation))
print("Yes, there is a positive relationship between shoe size and height.")


months_vector <- c("March","April","January","November","January",
                   "September","October","September","November","August",
                   "January","November","November","February","May","August",
                   "July","December","August","August","September","November","February",
                   "April")

factor_months_vector <- factor(months_vector)
print(factor_months_vector)


summary(months_vector)
summary(factor_months_vector)


direction <- c("East", "West", "North")
frequency <- c(1, 4, 3)

factor_data <- rep(direction, frequency)
print(factor_data)

new_order_data <- factor(factor_data, levels = c("East", "West", "North"))
print(new_order_data)


import_data <- read.csv("import_march.csv")
View(import_data)
print(import_data)


random_search <- function() {
  num <- readline(prompt = "Enter a number from 1 to 50: ")
  num <- as.integer(num)
  
  if (num < 1 || num > 50) {
    print("The number selected is beyond the range of 1 to 50")
  } else if (num == 20) {
    print("TRUE")
  } else {
    print(num)
  }
}


min_bills <- function(price) {
  bills <- c(1000, 500, 200, 100, 50)
  total_bills <- 0
  remaining <- price
  
  for (bill in bills) {
    count <- remaining %/% bill
    total_bills <- total_bills + count
    remaining <- remaining %% bill
  }
  
  print(paste("Minimum number of bills needed:", total_bills))
  return(total_bills)
}

min_bills(350)


students <- data.frame(
  Name = c("Annie", "Thea", "Steve", "Hanna"),
  Grade1 = c(85, 65, 75, 95),
  Grade2 = c(65, 75, 55, 75),
  Grade3 = c(85, 90, 80, 100),
  Grade4 = c(100, 90, 85, 90)
)

print(students)

for (i in 1:nrow(students)) {
  avg <- (students$Grade1[i] + students$Grade2[i] + students$Grade3[i] + students$Grade4[i]) / 4
  if (avg > 90) {
    print(paste(students$Name[i], "'s average grade this semester is", avg))
  }
}

for (j in 2:5) {
  test_avg <- (students[1, j] + students[2, j] + students[3, j] + students[4, j]) / 4
  if (test_avg < 80) {
    print(paste("The", j-1, "test was difficult."))
  }
}

for (i in 1:nrow(students)) {
  grades <- c(students$Grade1[i], students$Grade2[i], students$Grade3[i], students$Grade4[i])
  max_grade <- grades[1]
  for (grade in grades) {
    if (grade > max_grade) {
      max_grade <- grade
    }
  }
  if (max_grade > 90) {
    print(paste(students$Name[i], "'s highest grade this semester is", max_grade))
  }
}